name: groupting
description: "친구들과 함께 즐기는 신개념 소개팅"

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  country_code_picker: ^3.0.0
  package_info_plus: ^8.0.0
  flutter_email_sender: ^6.0.2
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  cloud_functions: ^5.0.2

  # State Management
  provider: ^6.1.1

  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  image: ^4.1.7

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

  # Utils
  intl: ^0.20.2
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^17.2.1+2
  http: ^1.1.0
  path_provider: ^2.1.1
  firebase_app_check: ^0.3.2+10
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"
    min_sdk_android: 21

# 스플래시 화면 설정
flutter_native_splash:
  color: "#FFFFFF" # 배경색 (흰색)
  image: "assets/splash_logo.png" # 스플래시 중앙에 들어갈 로고 이미지
  color_dark: "#FFFFFF" # 다크모드 배경색
  image_dark: "assets/splash_logo.png" # 다크모드 이미지

  # Android 12 이상 (스플래시 API 대응)
  android_12:
    image: "assets/splash_logo.png"
    color: "#FFFFFF"

  # 전체 화면 여부
  fullscreen: true